export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  CONFIRM_EMAIL: '/confirm',
  DASHBOARD: '/dashboard',
  STUDENTS: '/students',
  STUDENT_DETAIL: '/students/:id',
  ENROLLMENT_APPLICATION: '/enrollment-application/:childId',
  ENROLLMENT_TRACKING: '/enrollment-tracking',
  CLASSES: '/classes',
  PROFILE: '/profile',
  PAYMENT_HISTORY: '/payment-history',
  INVOICE_DETAIL: '/invoice-detail/:invoiceId',
  NEWS: '/news',
  ABOUT_US: '/about-us',
  CONTACT: '/contact',
  // Staff management routes
  STAFF: '/staff',
  STAFF_DASHBOARD: '/staff/dashboard',
  STAFF_STUDENTS: '/staff/students',
  STAFF_LIST: '/staff/list',
  STAFF_ADD: '/staff/add',
  STAFF_ATTENDANCE: '/staff/attendance',
  STAFF_SCHEDULE: '/staff/schedule',
  STAFF_PAYROLL: '/staff/payroll',
  STAFF_PERFORMANCE: '/staff/performance',
  STAFF_TRAINING: '/staff/training',
  STAFF_ASSIGN_STUDENTS: '/staff/assign-students',
};
