// <auto-generated />
using System;
using Infrastructure.EntitiesConfigurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250620113908_AddStatusIntoClassChildren")]
    partial class AddStatusIntoClassChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassChildrenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClassChildrenID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Domain.Entities.Children", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Childrens");
                });

            modelBuilder.Entity("Domain.Entities.ChildrenGrade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AcademicYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("GradeLevelID");

                    b.ToTable("ChildrenGrades");
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("EnrichmentProgramId")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SyllabusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EnrichmentProgramId");

                    b.HasIndex("GradeLevelID");

                    b.HasIndex("SyllabusID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Domain.Entities.ClassChildren", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassChildrens");
                });

            modelBuilder.Entity("Domain.Entities.ClassTeacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("TeacherID");

                    b.ToTable("ClassTeachers");
                });

            modelBuilder.Entity("Domain.Entities.EnrichmentProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeProgramID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TypeProgramID");

                    b.ToTable("EnrichmentPrograms");
                });

            modelBuilder.Entity("Domain.Entities.EnrollmentApplication", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int");

                    b.Property<Guid?>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("GradeLevelID");

                    b.HasIndex("InvoiceID")
                        .IsUnique()
                        .HasFilter("[InvoiceID] IS NOT NULL");

                    b.HasIndex("ParentID");

                    b.HasIndex("StaffID");

                    b.ToTable("EnrollmentApplications");
                });

            modelBuilder.Entity("Domain.Entities.GradeLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("GradeLevels");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ChildrenID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProgramID")
                        .HasColumnType("int");

                    b.Property<int?>("TuitionFeeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("TuitionFeeID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("Domain.Entities.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.Syllabus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Syllabi");
                });

            modelBuilder.Entity("Domain.Entities.SyllabusDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SyllabusID")
                        .IsUnique();

                    b.ToTable("SyllabusDetails");
                });

            modelBuilder.Entity("Domain.Entities.TuitionFee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GradeLevelID");

                    b.ToTable("TuitionFees");
                });

            modelBuilder.Entity("Domain.Entities.TypeProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypePrograms");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Domain.Entities.ClassChildren", "ClassChildrens")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassChildrens");
                });

            modelBuilder.Entity("Domain.Entities.Children", b =>
                {
                    b.HasOne("Domain.Entities.Account", "Parents")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("Domain.Entities.ChildrenGrade", b =>
                {
                    b.HasOne("Domain.Entities.Children", "Childrens")
                        .WithMany("ChildrenGrades")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.GradeLevel", "GradeLevels")
                        .WithMany("ChildrenGrades")
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Childrens");

                    b.Navigation("GradeLevels");
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.HasOne("Domain.Entities.EnrichmentProgram", "EnrichmentPrograms")
                        .WithMany("Classes")
                        .HasForeignKey("EnrichmentProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.GradeLevel", "GradeLevels")
                        .WithMany("Classes")
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Syllabus", "Syllabi")
                        .WithMany("Classes")
                        .HasForeignKey("SyllabusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnrichmentPrograms");

                    b.Navigation("GradeLevels");

                    b.Navigation("Syllabi");
                });

            modelBuilder.Entity("Domain.Entities.ClassChildren", b =>
                {
                    b.HasOne("Domain.Entities.Children", "Childrens")
                        .WithMany("ClassChildrens")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Class", "Classes")
                        .WithMany("ClassChildrens")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Childrens");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Domain.Entities.ClassTeacher", b =>
                {
                    b.HasOne("Domain.Entities.Class", "Classes")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Teachers")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.Entities.EnrichmentProgram", b =>
                {
                    b.HasOne("Domain.Entities.TypeProgram", "TypePrograms")
                        .WithMany("Programs")
                        .HasForeignKey("TypeProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypePrograms");
                });

            modelBuilder.Entity("Domain.Entities.EnrollmentApplication", b =>
                {
                    b.HasOne("Domain.Entities.Children", "Childrens")
                        .WithMany("EnrollmentApplications")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.GradeLevel", "GradeLevels")
                        .WithMany("EnrollmentApplications")
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Invoice", "Invoices")
                        .WithOne("EnrollmentApplications")
                        .HasForeignKey("Domain.Entities.EnrollmentApplication", "InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Account", "Parent")
                        .WithMany("ApplicationsSubmitted")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Staff")
                        .WithMany("ApplicationsApproved")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Childrens");

                    b.Navigation("GradeLevels");

                    b.Navigation("Invoices");

                    b.Navigation("Parent");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Account", "Accounts")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Children", "Childrens")
                        .WithMany("Invoices")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("Domain.Entities.Children", "Childrens")
                        .WithMany()
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Invoice", "Invoices")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EnrichmentProgram", "Programs")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TuitionFee", "TuitionFees")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("TuitionFeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Childrens");

                    b.Navigation("Invoices");

                    b.Navigation("Programs");

                    b.Navigation("TuitionFees");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.SyllabusDetail", b =>
                {
                    b.HasOne("Domain.Entities.Syllabus", "Syllabi")
                        .WithOne("SyllabusDetails")
                        .HasForeignKey("Domain.Entities.SyllabusDetail", "SyllabusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Syllabi");
                });

            modelBuilder.Entity("Domain.Entities.TuitionFee", b =>
                {
                    b.HasOne("Domain.Entities.GradeLevel", "GradeLevels")
                        .WithMany("TuitionFees")
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevels");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Navigation("ApplicationsApproved");

                    b.Navigation("ApplicationsSubmitted");

                    b.Navigation("Childrens");

                    b.Navigation("ClassTeachers");

                    b.Navigation("Invoices");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Children", b =>
                {
                    b.Navigation("ChildrenGrades");

                    b.Navigation("ClassChildrens");

                    b.Navigation("EnrollmentApplications");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.Navigation("ClassChildrens");

                    b.Navigation("ClassTeachers");
                });

            modelBuilder.Entity("Domain.Entities.ClassChildren", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Domain.Entities.EnrichmentProgram", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Domain.Entities.GradeLevel", b =>
                {
                    b.Navigation("ChildrenGrades");

                    b.Navigation("Classes");

                    b.Navigation("EnrollmentApplications");

                    b.Navigation("TuitionFees");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Navigation("EnrollmentApplications");

                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.Syllabus", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("SyllabusDetails");
                });

            modelBuilder.Entity("Domain.Entities.TuitionFee", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Domain.Entities.TypeProgram", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
