// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreSchoolBE.src.Infrastructure.EntitiesConfigurations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Attendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassChildrenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClassChildrenID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Children", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Childrens");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SyllabusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SyllabusID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.ClassChildren", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassChildrens");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.ClassTeacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("TeacherID");

                    b.ToTable("ClassTeachers");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.EnrichmentProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeProgramID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TypeProgramID");

                    b.ToTable("EnrichmentPrograms");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.EnrollmentApplication", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ProgramID");

                    b.ToTable("EnrollmentApplications");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Invoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ChildrenID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.InvoiceDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildrenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChildrenID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProgramID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Syllabus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotAmount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Syllabi");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.SyllabusDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("SyllabusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SyllabusID");

                    b.ToTable("SyllabusDetails");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.TypeProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypePrograms");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Account", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Attendance", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.ClassChildren", "ClassChildrens")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassChildrens");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Children", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Account", "Parents")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Class", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Syllabus", "Syllabi")
                        .WithMany("Classes")
                        .HasForeignKey("SyllabusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Syllabi");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.ClassChildren", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Children", "Childrens")
                        .WithMany("ClassChildrens")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Class", "Classes")
                        .WithMany("ClassChildrens")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Childrens");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.ClassTeacher", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Class", "Classes")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Account", "Teachers")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.EnrichmentProgram", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.TypeProgram", "TypePrograms")
                        .WithMany("Programs")
                        .HasForeignKey("TypeProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypePrograms");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.EnrollmentApplication", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Children", "Childrens")
                        .WithMany("EnrollmentApplications")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Account", "Accounts")
                        .WithMany("EnrollmentApplications")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.EnrichmentProgram", "Programs")
                        .WithMany("EnrollmentApplications")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Childrens");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Invoice", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Account", "Accounts")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Children", "Childrens")
                        .WithMany("Invoices")
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Children", "Childrens")
                        .WithMany()
                        .HasForeignKey("ChildrenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Invoice", "Invoices")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.EnrichmentProgram", "Programs")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Childrens");

                    b.Navigation("Invoices");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Notification", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.SyllabusDetail", b =>
                {
                    b.HasOne("PreSchoolBE.src.Infrastructure.Entities.Syllabus", "Syllabi")
                        .WithMany("SyllabusDetails")
                        .HasForeignKey("SyllabusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Syllabi");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Account", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("ClassTeachers");

                    b.Navigation("EnrollmentApplications");

                    b.Navigation("Invoices");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Children", b =>
                {
                    b.Navigation("ClassChildrens");

                    b.Navigation("EnrollmentApplications");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Class", b =>
                {
                    b.Navigation("ClassChildrens");

                    b.Navigation("ClassTeachers");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.ClassChildren", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.EnrichmentProgram", b =>
                {
                    b.Navigation("EnrollmentApplications");

                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.Syllabus", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("SyllabusDetails");
                });

            modelBuilder.Entity("PreSchoolBE.src.Infrastructure.Entities.TypeProgram", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
