import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faChildren, 
  faUser, 
  faCalendarDays, 
  faPlus, 
  faEdit, 
  faTrash,
  faTimes,
  faCheck,
  faPhone,
  faLock,
  faKey,
  faEye,
  faEyeSlash,
  faCog,
  faSignature,
  faBirthdayCake,
  faMars,
  faVenus,
  faCity,
  faMapMarkerAlt,
  faUserTie,
  faUserFriends,
  faUserCheck,
  faUserTimes,
  faChild,
  
} from '@fortawesome/free-solid-svg-icons';

// Đăng ký các icon sẽ sử dụng trong ứng dụng
library.add(
  faChildren,
  faUser,
  faCalendarDays,
  faPlus,
  faEdit,
  faTrash,
  faTimes,
  faCheck,
  faPhone,
  faLock,
  faKey,
  faEye,
  faEyeSlash,
  faCog,
  faSignature,
  faBirthdayCake,
  faMars,
  faVenus,
  faCity,
  faMapMarkerAlt,
  faUserTie,
  faUserFriends,
  faUserCheck,
  faUserTimes,
  faChild,
);

// Không cần export vì đã đăng ký vào library 